services:
  - type: web
    name: intelligent-resume-parser
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
